apiVersion: v1
kind: Secret
metadata:
  name: {{ required "secretName is required" .Values.secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
