apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-template.fullname" . }}
  namespace: {{ include "app-template.namespace" . }}
  labels:
    app: {{ include "app-template.fullname" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "app-template.fullname" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
