# Scans ${APP_IMAGE_REPO} for tags so the ImagePolicy can pick the newest one.
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: ${APP_NAME}-${APP_SERVICE_NAME}-${APP_ENV}
  namespace: flux-system
  labels:
    app.kubernetes.io/name: ${APP_NAME}-${APP_SERVICE_NAME}-${APP_ENV}
spec:
  image: ${APP_IMAGE_REPO}
  interval: 5m
